# Generated by Django 2.0.7 on 2018-07-19 12:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/news/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_for_only_partners',
            field=models.BooleanField(default=False, verbose_name='Только для партнёров?'),
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' ', verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
