# Generated by Django 2.0.7 on 2018-07-12 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='Код платежа')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Назначение платежа',
                'verbose_name_plural': 'Назначения платежей',
            },
        ),
        migrations.CreateModel(
            name='UsersFinanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('uuid', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Purpose', verbose_name='Назначение платежа')),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to=settings.AUTH_USER_MODEL, verbose_name='Второй пользователь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Финансы пользователей',
                'verbose_name_plural': 'Финансы пользователя',
            },
        ),
    ]
