# Generated by Django 2.0.7 on 2018-07-31 13:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payment-systems', verbose_name='Логотип')),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Настройки системы')),
                ('is_active', models.BooleanField(default=False, verbose_name='Является активной')),
            ],
            options={
                'verbose_name': 'Платёжная система',
                'verbose_name_plural': 'Платёжные системы',
            },
        ),
    ]
