# Generated by Django 2.0.7 on 2018-08-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='code',
            field=models.PositiveIntegerField(default=110, unique=True, verbose_name='Уникальный код системы'),
            preserve_default=False,
        ),
    ]
