# Generated by Django 2.0.7 on 2018-08-02 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20180802_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfinancehistory',
            name='second_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to=settings.AUTH_USER_MODEL, verbose_name='Второй пользователь'),
        ),
    ]
