# Generated by Django 2.0.7 on 2018-08-06 13:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20180802_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
