# Generated by Django 2.0.7 on 2018-08-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_blockiowallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockiowallet',
            name='balance',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='blockiowallet',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
