# Generated by Django 2.0.7 on 2018-08-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20180807_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockiowallet',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
