# Generated by Django 2.0.7 on 2018-08-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_blockiowallet_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockiowallet',
            name='balance_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
