# Generated by Django 2.0.7 on 2018-08-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_blockiowallet_balance_usd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersfinancehistory',
            options={'ordering': ('-id',), 'verbose_name': 'Финансы пользователей', 'verbose_name_plural': 'Финансы пользователя'},
        ),
    ]
