# Generated by Django 2.0.7 on 2018-12-02 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0012_auto_20180808_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Сумма')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('status', models.CharField(choices=[('1', 'Новый'), ('2', 'Отказано'), ('3', 'Выполнен')], max_length=1, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на вывод средств',
                'verbose_name_plural': 'Запросы на вывод средств',
            },
        ),
    ]
