# Generated by Django 2.0.7 on 2018-12-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_moneyrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneyrequest',
            options={'permissions': (('can_moderate_money_requests', 'Может модерировать вывод средств'),), 'verbose_name': 'Запрос на вывод средств', 'verbose_name_plural': 'Запросы на вывод средств'},
        ),
    ]
