# Generated by Django 2.0.7 on 2018-08-10 13:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import promo.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo/video-lessons/', verbose_name='Изображение')),
                ('video', models.URLField(blank=True, null=True, validators=[promo.validators.youtube_validator], verbose_name='YouTube Видео')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание урока')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Sorted')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='LessonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Sorted')),
            ],
            options={
                'verbose_name': 'Категория уроков',
                'verbose_name_plural': 'Категории уроков',
                'ordering': ('sort',),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.LessonCategory', verbose_name='Категория'),
        ),
    ]
