# Generated by Django 2.0.7 on 2018-08-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='promo/POS/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'POS материал',
                'verbose_name_plural': 'POS материалы',
            },
        ),
    ]
