# Generated by Django 2.0.7 on 2018-07-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('tokens', models.PositiveIntegerField(verbose_name='Токены')),
                ('bonuses', models.PositiveIntegerField(verbose_name='Бонусы')),
                ('weight', models.PositiveSmallIntegerField(default=1, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
                'ordering': ('weight',),
            },
        ),
        migrations.CreateModel(
            name='PackageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('old_package', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_pakcage', to='packages.Package', verbose_name='Предыдущий пакет')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Package history',
                'verbose_name_plural': 'Package histories',
            },
        ),
    ]
