# Generated by Django 2.0.7 on 2018-07-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_packagehistory_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagehistory',
            options={'verbose_name': 'История покупки пакетов', 'verbose_name_plural': 'Истории покупки пакетов'},
        ),
        migrations.AddField(
            model_name='package',
            name='points',
            field=models.PositiveIntegerField(default=100, verbose_name='Баллы'),
            preserve_default=False,
        ),
    ]
