# Generated by Django 2.0.7 on 2018-08-01 16:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20180712_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='Цвет пакета'),
        ),
    ]
