# Generated by Django 2.0.7 on 2018-07-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binary_tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binarytree',
            name='status',
        ),
    ]
