# Generated by Django 2.0.7 on 2018-07-12 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binary_tree', '0002_remove_binarytree_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarytree',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
