# Generated by Django 2.0.7 on 2018-07-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_user_is_in_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('1', 'Неактивный'), ('2', 'Активный'), ('3', 'Заморожен'), ('4', 'Полное заполнение')], default='1', max_length=1, verbose_name='Статус'),
        ),
    ]
