# Generated by Django 2.0.7 on 2018-07-16 15:29

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('user_profile', '0004_auto_20180712_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='vintkor', max_length=30, unique=True, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+380966136092', max_length=128, unique=True, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ref_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Aleksandr', max_length=40, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Aleksandr', max_length=40, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
