# Generated by Django 2.0.7 on 2018-07-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20180716_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
