# Generated by Django 2.0.7 on 2018-07-17 16:13

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20180717_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
