# Generated by Django 2.0.7 on 2018-07-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20180717_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
