# Generated by Django 2.0.7 on 2018-07-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20180712_1634'),
        ('user_profile', '0012_auto_20180717_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.Package', verbose_name='Пакет'),
        ),
    ]
