# Generated by Django 2.0.7 on 2018-07-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
        ('user_profile', '0013_user_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='awards.RangAward', verbose_name='Ранг'),
        ),
    ]
