# Generated by Django 2.0.7 on 2018-07-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_user_rang'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
