# Generated by Django 2.0.7 on 2018-07-24 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_user_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='verification', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Документ верификации',
                'verbose_name_plural': 'Документы верификации',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-unique_number'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_valid_email',
            field=models.BooleanField(default=False, verbose_name='Email валидный'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_valid_phone',
            field=models.BooleanField(default=False, verbose_name='Телефонный номер валидный'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
