# Generated by Django 2.0.7 on 2018-07-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_auto_20180724_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-unique_number'], 'permissions': (('is_verified', 'is_verified'),), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
