# Generated by Django 2.0.7 on 2018-07-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_auto_20180725_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='verification',
            field=models.CharField(blank=True, choices=[('1', 'Верифицирован'), ('2', 'Отказано'), ('3', 'Запрошены документы')], max_length=3, null=True, verbose_name='Верифицирован'),
        ),
    ]
