# Generated by Django 2.0.7 on 2018-08-13 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0020_auto_20180725_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привелигиированый пользователь',
                'verbose_name_plural': 'Привелигиированые пользователи',
            },
        ),
    ]
