# Generated by Django 2.0.7 on 2018-12-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_topusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='freeze_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Замороженные средства'),
        ),
    ]
