# Generated by Django 2.0.7 on 2018-07-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Заголовок'),
        ),
    ]
