# Generated by Django 2.0.7 on 2018-07-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RangAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объём')),
                ('max_lines', models.PositiveSmallIntegerField(verbose_name='Количество линий')),
                ('lines_volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объём в линиях')),
                ('include_rang_count', models.PositiveSmallIntegerField(verbose_name='Количество партнёров с указаным рангом')),
                ('include_rang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.RangAward', verbose_name='Ранг партнёров')),
            ],
            options={
                'verbose_name': 'Ранговый бонус',
                'verbose_name_plural': 'Ранговые бонусы',
            },
        ),
    ]
