# Generated by Django 2.0.7 on 2018-07-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangaward',
            name='include_rang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='awards.RangAward', verbose_name='Ранг партнёров'),
        ),
    ]
