# Generated by Django 2.0.7 on 2018-07-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20180720_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rangaward',
            options={'ordering': ('-volume',), 'verbose_name': 'Ранговый бонус', 'verbose_name_plural': 'Ранговые бонусы'},
        ),
        migrations.AddField(
            model_name='rangaward',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонус'),
            preserve_default=False,
        ),
    ]
