# Generated by Django 2.0.7 on 2018-07-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20180712_1634'),
        ('awards', '0005_multilevelbonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLevelBonusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('package_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.PackageHistory', verbose_name='Запись в истории')),
            ],
            options={
                'verbose_name': 'Отчёт по многоуровневому бонусу',
                'verbose_name_plural': 'Отчёты по многоуровневому бонусу',
            },
        ),
    ]
