# Generated by Django 2.0.7 on 2018-07-30 18:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_multilevelbonushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilevelbonushistory',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
