# Generated by Django 2.0.7 on 2018-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0008_rangawardhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangaward',
            name='quick_bonus',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Бонус быстрого старта'),
        ),
        migrations.AddField(
            model_name='rangaward',
            name='quick_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='К-во дней с момента регистрации'),
        ),
    ]
