# Generated by Django 2.0.7 on 2018-08-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0009_auto_20180804_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangaward',
            name='quick_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Бонус быстрого старта'),
        ),
    ]
