# Generated by Django 2.0.7 on 2018-08-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0012_rangaward_is_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangaward',
            name='weight',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Вес'),
        ),
    ]
