# Generated by Django 2.0.7 on 2018-08-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0013_rangaward_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бонус')),
                ('rang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.RangAward', verbose_name='Ранг')),
            ],
            options={
                'verbose_name': 'Схема конвертации баллов в FBC',
                'verbose_name_plural': 'Схемы конвертации баллов в FBC',
            },
        ),
    ]
